### PR TITLE
[ADD] tooltip component

### PR DESCRIPTION
**Pull request by ishak-lm**

### CODE REVIEW

**Comment by iherger** [comment]
The tooltip looks good.

We want to display all decimals of a displayed number, though. E.g. if the displayed number is `0.0015` the full number that appears with the tooltip will be `0.001539684733994326`

Since we want to show this pretty much everywhere, it's probably best to add this to the `<FormattedNumber>` component, so that it's shown as a standard. Maybe add an optional boolean prop `disableTooltip` to disable it if necessary.

**Comment by fubhy** [comment]
I think we should instead add this to this component: https://github.com/avantgardefinance/interface/blob/master/src/components/Common/TokenBalance/TokenBalance.tsx

And then use it everywhere where we display a value related to a specific token. For that we would have to make it optionally hide the token symbol suffix because e.g. in tables we don't want to show this.

**Comment by fubhy** [comment]
Actually, I agree with Ivan, let's add it to FormattedNumber and optionally *enable* it there but then in <TokenBalance> (I think we should rename this component then) we always enable it and show the full amount of decimals (up to 18) but also include the symbol.

**Comment by fubhy** [comment]
This looks good for now. We'll h ave to go through the app and add use the TokenBalance component (rename it to `TokenValue`) now more often and make sure it shows the tooltip for every token value that we render anywhere.

**Pull request merged**
